services:
  voice-mover:
    build: .
    container_name: voice-mover
    ports:
      - "3012:3000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:' + (process.env.PORT||3000) + '/api/voice', {headers:{'x-admin-key':process.env.ADMIN_SHARED_SECRET||'change-me'}}).then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    networks:
      - proxy

networks:
   proxy:
       name: proxy
       driver: bridge
       external: true
